AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mb-bankmutations

  Serverless application (SAM) for transfering bank csv files into Moneybird with API
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  BankFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: app.handler
      Runtime: nodejs10.x
      Events:
        Config:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /config/{path+}
            Method: any
        Files:
          Type: Api
          Properties:
            Path: /files/{path+}
            Method: any

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ConfigApi:
    Description: "API Gateway endpoint URL for Config function of Bank"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/config/"
  FilesApi:
    Description: "API Gateway endpoint URL for Files function of Bank"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/files/"
  BankFunction:
    Description: "Bank Lambda Function ARN"
    Value: !GetAtt BankFunction.Arn
  BankFunctionIamRole:
    Description: "Implicit IAM Role created for Bank function"
    Value: !GetAtt BankFunctionRole.Arn
